// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApp._Internal.Repositories;

namespace WebApp.Migrations
{
    [DbContext(typeof(OrdersRepository))]
    [Migration("20190811203124_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WebApp._Internal.Entities.OrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnName("created");

                    b.Property<int>("Status")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTimeOffset(new DateTime(2019, 8, 11, 23, 31, 24, 691, DateTimeKind.Unspecified).AddTicks(2503), new TimeSpan(0, 3, 0, 0, 0)),
                            Status = 1
                        });
                });

            modelBuilder.Entity("WebApp._Internal.Entities.OrderProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int?>("OrderEntityId");

                    b.Property<int?>("OrderId");

                    b.Property<int?>("ProductEntityId");

                    b.Property<int?>("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("OrderEntityId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductEntityId");

                    b.HasIndex("ProductId");

                    b.ToTable("order_vs_product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("811ae373-1408-483f-ac3e-babcbb1dcaaf"),
                            OrderEntityId = 1,
                            OrderId = 1,
                            ProductEntityId = 1,
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("WebApp._Internal.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TestProduct1",
                            Price = 12.199999999999999,
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("WebApp._Internal.Entities.OrderProductEntity", b =>
                {
                    b.HasOne("WebApp._Internal.Entities.OrderEntity")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderEntityId");

                    b.HasOne("WebApp._Internal.Entities.OrderEntity", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.HasOne("WebApp._Internal.Entities.ProductEntity")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductEntityId");

                    b.HasOne("WebApp._Internal.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
